"""Initial migration

Revision ID: be1d5e3fd3ff
Revises: 
Create Date: 2020-05-14 20:25:56.190429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1d5e3fd3ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('paassword_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('blog_title', sa.VARCHAR(length=60), nullable=True),
    sa.Column('blog_sub_title', sa.VARCHAR(length=100), nullable=True),
    sa.Column('name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
